version: '3.5'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./capture:/var/www/capture
      
  ffmpeg:
    build:
      context: ./ffmpeg
    volumes:
      - ./capture:/capture
